//_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.11-2021/01/28-beta
`include "sp_verilog.vh" //_\SV
   // Included URL: "https://raw.githubusercontent.com/BalaDhinesh/Virtual-FPGA-Lab/main/viz_libraries/includes.tlv"                   
//_\SV
   
   
   
   module top(input clk, input reset, output [15:0] led);
      clock_divider #(.DIV_VALUE(24999999)) dut1 (clk, divided_clk);
      test dut2 (divided_clk, reset, led);
   endmodule
   module test (input clk, input reset, output [15:0] led);
   
         
`include "led_counter_gen.v"
generate //_\TLV
   //_|led_pipe
      //_@0  
         assign LED_PIPE_reset_a0 = reset;
         assign LED_PIPE_leds_a0[15:0] = LED_PIPE_reset_a0 ? 0 : LED_PIPE_leds_a1+1;
         
         
         
         
         assign led = LED_PIPE_leds_a0;
endgenerate
         
         
   
   
   
   
   
   
//_\SV
   endmodule
