// Generated by SandPiper(TM) 1.11-2021/01/28-beta from Redwood EDA.
// Redwood EDA does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


`include "sandpiper_gen.vh"





//
// Signals declared top-level.
//

// For |led_pipe$leds.
wire [15:0] LED_PIPE_leds_a0;
reg  [15:0] LED_PIPE_leds_a1;

// For |led_pipe$reset.
wire LED_PIPE_reset_a0;



generate


   //
   // Scope: |led_pipe
   //

      // For $leds.
      always @(posedge clk) LED_PIPE_leds_a1[15:0] <= LED_PIPE_leds_a0[15:0];




endgenerate

